apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: current-time-api
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/ymohan350/kubernetes-ci-cd-demo.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
